version: 0.2

env:
  variables:
    AWS_REGION: ap-south-1
    ECR_REPO: galani-enterprise

phases:
  pre_build:
    commands:
      - echo Logging in to Amazon ECR...
      - aws --version
      - aws ecr get-login-password --region $AWS_REGION | docker login --username AWS --password-stdin 209483893123.dkr.ecr.$AWS_REGION.amazonaws.com
      - IMAGE_TAG=$(echo $CODEBUILD_RESOLVED_SOURCE_VERSION | cut -c 1-7)

  build:
    commands:
      - echo Build started on `date`
      - docker build -t $ECR_REPO:$IMAGE_TAG .
      - docker tag $ECR_REPO:$IMAGE_TAG 209483893123.dkr.ecr.$AWS_REGION.amazonaws.com/$ECR_REPO:$IMAGE_TAG
      - docker tag $ECR_REPO:$IMAGE_TAG 209483893123.dkr.ecr.$AWS_REGION.amazonaws.com/$ECR_REPO:latest

  post_build:
    commands:
      - echo Pushing Docker images...
      - docker push 209483893123.dkr.ecr.$AWS_REGION.amazonaws.com/$ECR_REPO:$IMAGE_TAG
      - docker push 209483893123.dkr.ecr.$AWS_REGION.amazonaws.com/$ECR_REPO:latest
      - echo Build completed on `date`

artifacts:
  files:
    - '**/*'
