steps:
  # --- UAAL POLICY CHECK (SHADOW MODE DEFAULT) ---
  - name: 'python:3.10-slim'
    id: 'uaal-policy-check'
    entrypoint: 'bash'
    args:
      - -c
      - |
        python uaal_ci_check.py
    env:
      - 'UAAL_SHADOW_MODE=true'

  # --- BUILD IMAGE WITH POLICY METADATA ---
  - name: 'gcr.io/cloud-builders/docker'
    id: 'docker-build'
    entrypoint: 'bash'
    args:
      - -c
      - |
        docker build \
          --label uaal.decision=$(cat uaal_decision.txt) \
          --label uaal.mode=shadow \
          --label uaal.commit=$COMMIT_SHA \
          -t gcr.io/$PROJECT_ID/privatevault-api:$COMMIT_SHA .

  # --- PUSH IMAGE ---
  - name: 'gcr.io/cloud-builders/docker'
    id: 'docker-push'
    args:
      - push
      - gcr.io/$PROJECT_ID/privatevault-api:$COMMIT_SHA

images:
  - gcr.io/$PROJECT_ID/privatevault-api:$COMMIT_SHA
