version: 2

project_name: privatevault

before:
  hooks:
    - go mod tidy

builds:
  - id: privatevault
    main: ./main.go
    binary: privatevault
    env:
      - CGO_ENABLED=0
    goos: [linux, darwin, windows]
    goarch: [amd64, arm64]
    ldflags:
      - -s -w
      - -X "main.version={{ .Version }}"
      - -X "main.commit={{ .Commit }}"
      - -X "main.date={{ .Date }}"

archives:
  - id: default
    builds: [privatevault]
    format: binary
    name_template: "{{ .ProjectName }}-{{ .Os }}-{{ .Arch }}"

checksum:
  name_template: "checksums.txt"

release:
  github:
    owner: LOLA0786
    name: PrivateVault-Mega-Repo

brews:
  - name: privatevault
    description: "PrivateVault CLI: secure agent control plane + AI firewall"
    homepage: "https://github.com/LOLA0786/PrivateVault-Mega-Repo"
    license: "Apache-2.0"

    repository:
      owner: LOLA0786
      name: homebrew-privatevault
      branch: main
      token: "{{ .Env.GITHUB_TOKEN }}"

    directory: Formula

    url_template: "https://github.com/LOLA0786/PrivateVault-Mega-Repo/releases/download/{{ .Tag }}/{{ .ArtifactName }}"

    test: |
      system "#{bin}/privatevault", "version"
