version: 2

project_name: privatevault

before:
  hooks:
    - go mod tidy

builds:
  - id: privatevault
    main: .
    binary: privatevault
    env:
      - CGO_ENABLED=0
    goos:
      - linux
      - darwin
      - windows
    goarch:
      - amd64
      - arm64

archives:
  - id: default
    format: binary
    name_template: "{{ .ProjectName }}-{{ .Os }}-{{ .Arch }}"

checksum:
  name_template: "checksums.txt"

changelog:
  sort: asc
  filters:
    exclude:
      - "^docs:"
      - "^test:"

brews:
  - name: privatevault
    homepage: "https://github.com/LOLA0786/PrivateVault-Mega-Repo"
    description: "PrivateVault CLI: security control plane for AI agents"
    license: "MIT"

    repository:
      owner: LOLA0786
      name: homebrew-privatevault
      branch: main
      token: "{{ .Env.GITHUB_TOKEN }}"

    directory: Formula

    commit_author:
      name: "PrivateVault Bot"
      email: "bot@privatevault.ai"

    install: |
      bin.install "privatevault"

    test: |
      system "#{bin}/privatevault", "version"
